---
title: "NYC House Prices vs. High School Diploma"
author: "Thu Dang, Nathaniel Reimer, Jeremy Hubinger"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warnings=FALSE)
```

```{r}
library(dplyr)
library(lubridate)
library(stringr)
library(ggplot2)
library(sf) #install.packages('sf')
library(spdep) #install.packages('spdep')
library(patchwork)
library(viridis)
library(MetBrewer)
library(tidycensus)
library(tidygeocoder)
library(dplyr)
# library(googlesheets4)
library(readr)
library(tidyr)
library(gganimate)
library(gifski)
library(transformr)
```

```{r}
# Load nyc data from 2015 to 2019
load('NYCHousingEduData.RData')
```

```{r}
# Animation

p1 <- nyc_house_data_2015_2019_clean %>%
  filter(!is.na(HouseValueE)) %>%
  ggplot() +
  geom_sf(aes(fill = HouseValueE, group=year), size = 0) +
  scale_fill_viridis_c() +
  scale_size(range = c(2, 12)) +
  labs(title = 'Year: {floor(frame_time)}', subtitle = 'Median House Prices in New York City') +
  theme_void() +
  transition_time(year)

# animate(p1, duration = 20)

anim_save("nyc_house_price_animation.gif")
```


```{r}
nyc_house_data_2015_2019_clean %>%
  separate_wider_delim(NAME, ",", names = c("Census Tract Number", "County Name", "State")) %>%
  st_as_sf() %>%
  ggplot(aes(fill=`County Name`), size=0) +
  geom_sf() +
  scale_fill_manual(values = met.brewer("Signac", 5)) +
  # scale_fill_viridis(discrete=TRUE, option="discrete") +
  scale_size(range = c(2, 12)) +
  theme_void()
```

```{r}
nyc_house_data_2015_2019_clean <- nyc_house_data_2015_2019_clean %>%
  mutate(HSDipPercent = (NumWithHighSchoolDiplomaE/PopE)*100)

nyc_house_data_2015_2019_clean %>% 
  filter(year == 2019) %>%
  drop_na(HSDipPercent,HouseValueE) %>%
  ggplot(aes(x=HouseValueE, y=HSDipPercent)) + 
  geom_point() + 
  geom_smooth() +
  theme_classic()
```
  
